spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: aa123456


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: site.yanbin.entity
  configuration:
    map-underscore-to-camel-case: true